chunk_size: 256
local_cpu: True
max_local_cpu_size: 80

# cache controller configurations
enable_controller: True
lmcache_instance_id: "lmcache_helium_0"
controller_url: "localhost:9001"
lmcache_worker_port: 8001

distributed_url: "localhost:8201"
